### PR TITLE
fix: allow adding class names to fab logo

### PR DESCRIPTION
**Pull request by acostalima**
Created `logoClassName` prop in `DiscussionFab` component to enable supply of CSS classes to FAB's logo.

### CODE REVIEW

**Comment by acostalima** [comment]
@satazor @PedroMiguelSS

**Comment by satazor** [comment]
Looks good, could you update the component's readme to add this new prop?

**Comment by acostalima** [comment]
> Looks good, could you update the component's readme to add this new prop?

Will do. Thanks!

**Comment by acostalima** [comment]
It should be good to go now.

**Review by PedroMiguelSS — APPROVED** [review]
SGTM 👍

**Pull request merged**
